# Created by Crt Vavros, copyright © 2022 ZeroPass. All rights reserved.
name: mrtdeg
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.2.1

environment:
  sdk: '>=2.17.1 <4.0.0'

publish_to: none

dependencies:
  flutter:
    sdk: flutter
  permission_handler: ^11.0.1
  archive: ^3.1.2
  collection: ^1.16.0
  convert: ^3.0.0
  crypto: ^3.0.1
  expandable: ^5.0.1
  fixnum: ^1.0.0
  flutter_nfc_kit: ^3.3.1
  logging: ^1.0.1
  meta: ^1.3.0
  tripledes_nullsafety: ^1.0.3
  pointycastle: ^3.7.3
  intl: ^0.19.0
  google_mlkit_text_recognition: ^0.4.0
  camera: ^0.10.0+4
  google_mlkit_commons: ^0.2.0
  camera_platform_interface: ^2.2.2
  google_fonts: ^6.1.0
  font_awesome_flutter: ^10.6.0
  local_auth:
  lottie: ^3.1.0
  showcaseview : ^2.1.1
  shared_preferences: ^2.0.13
  json_annotation: ^4.7.0
  sqflite: any
  path: any
  cupertino_icons: ^1.0.2
  jdenticon_dart: ^2.0.0
  flutter_svg: ^2.0.10+1
  rflutter_alert: ^2.0.2
  web3dart: any
  confetti: any
  qr_code_scanner: ^1.0.1
  nice_buttons: ^0.0.3
  enhance_stepper:
  flutter_beautiful_popup:
  animated_text_kit: ^4.2.1
  liquid_pull_to_refresh :
  flutter_staggered_grid_view: ^0.6.1
  carousel_slider: ^4.0.0



  flutter_face_api: ^4.1.1
  image_picker: ^0.8.6
  firebase_core: ^2.5.0
  cloud_firestore: ^4.4.0
  uuid: ^3.0.7
  google_mlkit_face_detection: ^0.5.0
  audioplayers: ^6.0.0
  fl_chart: ^0.68.0
  awesome_dialog: ^3.2.1







dev_dependencies:
  flutter_launcher_icons: "^0.11.0"
  json_serializable: ^6.5.1
  build_runner: ^2.3.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/app_logo.jpg"

  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0




# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:

  assets:
    - assets/
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

